[{"Arizona":[["Scottsdale-Fashion Square","https://www.tesla.com/findus/location/store/fashionsquare",
["7014 E. Camelback Road\n","Suite #1210\n","Scottsdale, AZ 85251\n"]],
["Scottsdale-Kierland Commons","https://www.tesla.com/findus/location/store/scottsdalekierlandcommons",
["15215 N. Kierland Blvd #165B1A\n","Scottsdale, AZ 85254\n"]]],

"California":[["Brea-Brea Mall","https://www.tesla.com/findus/location/store/breamall",
["1065 Brea Mall\n","Brea, CA 92821\n"]],
["Buena Park","https://www.tesla.com/findus/location/store/buenapark",
["6692 Auto Center Drive\n","Buena Park, CA 90621\n"]],
["Burbank","https://www.tesla.com/findus/location/store/burbank",
["811 S San Fernando Blvd\n","Burbank, CA 91502\n"]],
["Burlingame","https://www.tesla.com/findus/location/store/burlingame",
["50 Edwards Court\n","Burlingame, CA 94010\n"]],
["Canoga Park-Topanga","https://www.tesla.com/findus/location/store/topanga",
["6600 Topanga Canyon Blvd\n","Suite 1049\n","Canoga Park, CA 91303\n"]],
["Carlsbad","https://www.tesla.com/findus/location/store/carlsbad",
["3248 Lionshead Avenue\n","Carlsbad, CA 92010\n"]],
["Corte Madera-The Village at Corte Madera","https://www.tesla.com/findus/location/store/villageatcortemadera",
["1616 Redwood Highway\n","Corte Madera, CA 94925\n"]],
["Costa Mesa","https://www.tesla.com/findus/location/store/costamesa",
["3140 Pullman Road\n","Costa Mesa, CA 92626\n"]],
["Dublin-Amador Plaza","https://www.tesla.com/findus/location/store/dublinamador",
["6701 Amador Plaza Road\n","Dublin, CA 94568\n"]],
["Fremont","https://www.tesla.com/findus/location/store/fremont",
["45500 Fremont Blvd\n","Fremont, CA 94538\n"]],
["Fresno","https://www.tesla.com/findus/location/store/fresnoservice",
["2988 N. Burl Ave.\n","Fresno, CA 93727\n"]],
["Glendale-Americana at Brand","https://www.tesla.com/findus/location/store/glendaleamericana",
["539 Americana Way\n","Glendale, CA 91210\n"]],
["Lake Forest","https://www.tesla.com/findus/location/store/lakeforest",
["25471 Arctic Ocean Dr\n","Lake Forest, CA 92630-8832\n"]],
["Los Angeles - Century City","https://www.tesla.com/findus/location/store/centurycity",
["10250 Santa Monica Blvd\n","Ste. 1340\n","Los Angeles, CA 90067\n"]],
["Los Angeles-Centinela","https://www.tesla.com/findus/location/store/centinela",
["5840 W. Centinela Ave\n","Los Angeles, CA 90045\n"]],
["Marina Del Rey-Alla Road","https://www.tesla.com/findus/location/store/marinadelrey",
["4755 Alla Road\n","Marina Del Rey, CA 90292\n"]],
["Mission Viejo-Shops at Mission Viejo","https://www.tesla.com/findus/location/store/shopsatmissionviejo",
["820 The Shops At Mission Viejo\n","Mission Viejo, CA 92691\n"]],
["Monterey-Seaside","https://www.tesla.com/findus/location/store/montereyseaside",
["1901 Del Monte Blvd\n","Seaside, CA 93955\n"]],
["Newport Beach-Fashion Island","https://www.tesla.com/findus/location/store/fashionisland",
["367 Newport Center Drive\n","Newport Beach, CA 92660\n"]],
["Palm Springs-Cathedral City","https://www.tesla.com/findus/location/store/cathedralcity",
["68080 Perez Road\n","Palm Springs, CA 92234\n"]],
["Palo Alto","https://www.tesla.com/findus/location/store/paloalto",
["4180 El Camino Real\n","Palo Alto, CA 94306\n"]],
["Palo Alto-Stanford Shopping Center","https://www.tesla.com/findus/location/store/stanfordshoppingcenter",
["660 Stanford Shopping Center\n","Palo Alto, CA 94304\n"]],
["Pasadena-Colorado Blvd","https://www.tesla.com/findus/location/store/pasadena",
["117 West Colorado Blvd\n","Pasadena, CA 91105\n"]],
["Rancho Cucamonga-Edison Ct.","https://www.tesla.com/findus/location/store/ranchocucamongaedisonct",
["10851 Edison Ct.\n","Rancho Cucamonga, CA 91730\n"]],
["Sacramento-Rocklin","https://www.tesla.com/findus/location/store/rocklin",
["4361 Granite Drive\n","Rocklin, CA 95677\n"]],
["San Diego - Fashion Valley","https://www.tesla.com/findus/location/store/sandiegofashionvalley",
["7007 Friars Road\n","Suite 325A\n","San Diego, CA 92108\n"]],
["San Diego-UTC","https://www.tesla.com/findus/location/store/universitytownecentre",
["4545 La Jolla Village Drive\n","Suite C17\n","San Diego, CA 92122\n"]],
["San Francisco - Van Ness","https://www.tesla.com/findus/location/store/sanfranciscovanness",
["999 Van Ness Avenue\n","San Francisco, CA 94109\n"]],
["San Jose-Santana Row","https://www.tesla.com/findus/location/store/santanarow",
["333 Santana Row Suite 1015\n","San Jose, CA 95128\n"]],
["Santa Barbara-Hitchcock Way","https://www.tesla.com/findus/location/store/santabarbara",
["400 Hitchcock Way\n","Santa Barbara, CA 93105\n"]],
["Santa Monica Place","https://www.tesla.com/findus/location/store/santamonicaplace",
["395 Santa Monica Place #120\n","Santa Monica, CA 90401\n"]],
["Serramonte-1500 Collins Ave","https://www.tesla.com/findus/location/store/serramonte1500collinsave",
["1500 Collins Ave\n","Colma, CA 94014\n"]],
["Sherman Oaks - Fashion Square Mall","https://www.tesla.com/findus/location/store/shermanoaksfashionsquaremall",
["14006 Riverside Dr. Space 78\n","Sherman Oaks, CA 91423\n"]],
["Sunnyvale","https://www.tesla.com/findus/location/store/sunnyvale",
["750 E El Camino Real\n","Sunnyvale, CA 94087\n"]],
["Torrance-Del Amo Mall","https://www.tesla.com/findus/location/store/torrancedelamomall",
["3525 W Carson St. Space 419\n","Torrance, CA 90503\n"]],
["Walnut Creek-Broadway Plaza","https://www.tesla.com/findus/location/store/walnutcreek",
["1246 Broadway Plaza Suite 1094\n","Walnut Creek, CA 94596\n"]]],

"Colorado":[["Cherry Creek","https://www.tesla.com/findus/location/store/cherrycreek",
["3000 E 1st Ave Space #148\n","Denver, CO 80206\n"]],
["Littleton-Broadway","https://www.tesla.com/findus/location/store/littletonbroadway",
["5700 S Broadway\n","Littleton, CO 80121\n"]],
["Lone Tree-Park Meadows","https://www.tesla.com/findus/location/store/parkmeadows",
["8401 Park Meadows Center Dr, Suite #1650\n","Lone Tree, CO 80124\n"]],
["Superior","https://www.tesla.com/findus/location/store/superior",
["2 S. Marshall Rd\n","Superior, CO 80027\n"]]],

"Connecticut":[["Milford","https://www.tesla.com/findus/location/store/milford",
["881 Boston Post Road\n","Milford, CT 6460\n"]]],

"Delaware":[["Christiana Mall","https://www.tesla.com/findus/location/store/christianamall",
["132 Christiana Mall Space 1401\n","Newark, DE 19702\n"]]],

"District of Columbia":[["CityCenterDC","https://www.tesla.com/findus/location/store/dccitycenter",
["909 H Street NW Suite 601\n","Washington DC, DC 20001\n"]]],

"Florida":[["Aventura-Aventura Mall","https://www.tesla.com/findus/location/store/aventuralmall",
["19565 Biscayne Blvd #1948\n","Aventura, FL 33180\n"]],
["Boca Raton-Town Center at Boca Raton","https://www.tesla.com/findus/location/store/bocatowncenter",
["6000 Glades Rd Suite 1121A\n","Boca Raton, FL 33431\n"]],
["Coral Gables","https://www.tesla.com/findus/location/store/coralgables",
["3851 Bird Road\n","Miami, FL 33146\n"]],
["Dania Beach","https://www.tesla.com/findus/location/store/daniabeach",
["1949 Tigertail Boulevard\n","Dania Beach, FL 33004\n"]],
["Estero-Coconut Point Mall","https://www.tesla.com/findus/location/store/esterococonutpointmall",
["23101 Fashion Drive, Suite 113\n","Estero, FL 33928-2506\n"]],
["Jacksonville-St. Johns Town Center","https://www.tesla.com/findus/location/store/jacksonville",
["4835 River City Drive Suite 105\n","Jacksonville, FL 32246\n"]],
["Miami-Dadeland","https://www.tesla.com/findus/location/store/dadeland",
["7535 N. Kendall Drive\n","Miami, FL 33156\n"]],
["Miami-Design District","https://www.tesla.com/findus/location/store/miamidesigndistrict",
["151 NE 41st Street, Suite 125\n","Miami, FL 33137\n"]],
["Naples-Waterside Shops","https://www.tesla.com/findus/location/store/napleswatersideshops",
["5415 Tamiami Trail N. H-2\n","Naples, FL 34108\n"]],
["Orlando - Florida Mall Showroom","https://www.tesla.com/findus/location/store/orlandofloridamall",
["8001 S Orange Blossom Trail Space 1280A\n","Orlando, FL 32809\n"]],
["Orlando-Eatonville","https://www.tesla.com/findus/location/store/orlando",
["100 S Lake Destiny Rd\n","Eatonville, FL 32810\n"]],
["Palm Beach Gardens – The Gardens Mall","https://www.tesla.com/findus/location/store/gardensmallpalmbeach",
["3101 PGA Boulevard, Store Q-215\n","Palm Beach Gardens, FL 33410\n"]],
["Sarasota-University Town Center","https://www.tesla.com/findus/location/store/sarasota",
["140 University Town Center Drive\n","Suite 138\n","Sarasota, FL 34243\n"]],
["Tampa - International Plaza","https://www.tesla.com/findus/location/store/tampainternationalplaza",
["2223 N Westshore Blvd Suite #269\n","Tampa, FL 33607\n"]],
["Tampa-Florida Ave","https://www.tesla.com/findus/location/store/tampafloridaave",
["11945 N. Florida Ave\n","Tampa, FL 33612\n"]],
["West Palm Beach – Okeechobee Blvd","https://www.tesla.com/findus/location/store/westplambeachokeechobee",
["5544 Okeechobee Blvd\n","West Palm Beach, FL 33417\n"]]],

"Georgia":[["Alpharetta","https://www.tesla.com/findus/location/store/alpharetta",
["6165 Avalon Boulevard\n","Alpharetta, GA 30009\n"]],
["Alpharetta-Roswell","https://www.tesla.com/findus/location/store/alpharettaroswell",
["1400 Upper Hembree Rd\n","Roswell, GA 30076\n"]],
["Atlanta-Decatur","https://www.tesla.com/findus/location/store/atlantadecatur",
["1580 Church St\n","Decatur, GA 30033\n"]]],

"Hawaii":[["Honolulu-Ala Moana Center","https://www.tesla.com/findus/location/store/alamoana",
["1450 Ala Moana Blvd Suite 2035\n","Honolulu, HI 96814\n"]],
["International Market Place","https://www.tesla.com/findus/location/store/hiinternationalmarketplace",
["2330 Kalakaua Ave Level 1 Banyan Court\n","Honolulu, HI 96815\n"]]],

"Idaho":[["Boise-Beverly Street","https://www.tesla.com/findus/location/store/boisebeverlyst",
["2592 S Beverly Street Bldg B Suite 126\n","Boise, ID 83709\n"]]],

"Illinois":[["Bloomington-Olympia Drive","https://www.tesla.com/findus/location/store/bloomingtonolympia",
["420 Olympia Dr\n","Bloomington, IL 61704\n"]],
["Chicago-Gold Coast","https://www.tesla.com/findus/location/store/chicagogoldcoast",
["901 North Rush Street\n","Chicago, IL 60611\n"]],
["Chicago-Highland Park","https://www.tesla.com/findus/location/store/highlandpark",
["1200 Old Skokie Valley Road\n","Highland Park, IL 60035\n"]],
["Chicago-Schaumburg","https://www.tesla.com/findus/location/store/chicagonwsuburbs",
["320 W. Golf Rd\n","Schaumburg, IL 60195-3608\n"]],
["Chicago-West Grand Avenue","https://www.tesla.com/findus/location/store/chicagograndave",
["1053 W. Grand Avenue\n","Chicago, IL 60642\n"]],
["Chicago-Westmont","https://www.tesla.com/findus/location/store/chicagowestmont",
["50 W. Ogden Ave\n","Westmont, IL 60559\n"]],
["Naperville","https://www.tesla.com/findus/location/store/naperville",
["3200 Ogden Ave\n","Lisle, IL 60532\n"]]],

"Indiana":[["Indianapolis","https://www.tesla.com/findus/location/store/indianapolis",
["8280 Castleton Corner Drive\n","Indianapolis, IN 46250\n"]]],

"Maryland":[["Baltimore-Owings Mills","https://www.tesla.com/findus/location/store/baltimoreowingsmill",
["9428 Reisterstown Road\n","Owings Mills, MD 21117\n"]],
["Bethesda-Montgomery Mall","https://www.tesla.com/findus/location/store/montgomerymall",
["Suite 1272\n","Bethesda, MD 20817\n"]]],

"Massachusetts":[["Boston-Boylston Street","https://www.tesla.com/findus/location/store/bostonboylstonstreet",
["888 Boylston Street Ste 055\n","Boston, MA 02116\n"]],
["Dedham","https://www.tesla.com/findus/location/store/dedham",
["840 Providence Highway\n","Dedham, MA 02026\n"]],
["Natick Mall","https://www.tesla.com/findus/location/store/natickmall",
["1245 Worcester St. Space 3018\n","Natick, MA 1760\n"]],
["Peabody-North Shore","https://www.tesla.com/findus/location/store/peabodynorthshore",
["210 Andover St\n","Peabody, MA 01960\n"]]],

"Michigan":[["Detroit-Clarkston","https://www.tesla.com/findus/location/store/detroitclarkson",
["8105 Big Lake Rd\n","Clarkston, MI 48346-1001\n"]],
["Somerset Collection","https://www.tesla.com/findus/location/store/somersetcollection",
["2800 W. Big Beaver Road Space #N-114\n","Troy, MI 48084\n"]]],

"Minnesota":[["Minneapolis-Eden Prairie","https://www.tesla.com/findus/location/store/edenprairie",
["6801 Washington Ave S\n","Suite 110\n","Minneapolis, MN 55439\n"]],
["St. Paul-Maplewood","https://www.tesla.com/findus/location/store/stpaulmn",
["2590 W. Maplewood Drive\n","Minneapolis, MN 55109\n"]]],

"Missouri":[["Kansas City-Stateline Road","https://www.tesla.com/findus/location/store/kansascitystateline",
["10111 State Line Rd\n","Kansas City, MO 64114-4262\n"]],
["St. Louis-Chesterfield","https://www.tesla.com/findus/location/store/stlouischesterfield",
["16955 Chesterfield Airport Road\n","Chesterfield, MO 63005-1405\n"]]],

"Nevada":[["Las Vegas-W. Sahara Ave","https://www.tesla.com/findus/location/store/lasvegaswsaharaave",
["7077 W Sahara Ave\n","Las Vegas, NV 89117\n"]],
["Reno-Virginia Street","https://www.tesla.com/findus/location/store/renovrginastreetservice",
["9732 S Virginia Street\n","Reno, NV 89511-5941\n"]]],

"New Jersey":[["Cherry Hill","https://www.tesla.com/findus/location/store/njcherryhill",
["1605 Route 70 West\n","Cherry Hill, NJ 8002\n"]],
["Garden State Plaza","https://www.tesla.com/findus/location/store/gardenstateplaza",
["One Garden State Plaza\n","Suite 2124\n","Paramus, NJ 07652\n"]],
["Lawrence Township-Princeton","https://www.tesla.com/findus/location/store/lawrencetownshipprinceton",
["3371 Brunswick Pike\n","Lawrence Township, NJ 08648\n"]],
["Paramus-Route 17","https://www.tesla.com/findus/location/store/paramusroute17",
["530 Route 17 N\n","Paramus, NJ 07652\n"]],
["Short Hills-Short Hills Mall","https://www.tesla.com/findus/location/store/shorthills",
["1200 Morris Turnpike\n","Short Hills, NJ 7078\n"]],
["Springfield","https://www.tesla.com/findus/location/store/springfieldnj",
["135 US 22\n","Springfield, NJ 7081\n"]]],

"New York":[["Brooklyn-Van Brunt Street","https://www.tesla.com/findus/location/store/brooklyn",
["160 Van Brunt Street\n","Brooklyn, NY 11231\n"]],
["Henrietta","https://www.tesla.com/findus/location/store/henriettaservice",
["3300 W Henrietta Rd\n","Henrietta, NY 14623\n"]],
["Huntington Station-Walt Whitman Shops","https://www.tesla.com/findus/location/store/waltwhitman",
["160 Walt Whitman Rd\n","Space 1009A\n","Huntington Station, NY 11746\n"]],
["Manhasset-Americana Manhasset","https://www.tesla.com/findus/location/store/americanamanhassetdelivery",
["2122 Northern Blvd\n","Manhasset, NY 11030\n"]],
["Meatpacking-860 Washington","https://www.tesla.com/findus/location/store/860washington",
["860 Washington St.\n","New York, NY 10014\n"]],
["Smithtown-Long Island","https://www.tesla.com/findus/location/store/smithtownlongisland",
["1000 Nesconset Highway\n","Smithtown, NY 11787-1066\n"]],
["Westchester-Mt. Kisco","https://www.tesla.com/findus/location/store/mtkisco",
["115 Kisco Avenue\n","Mt. Kisco, NY 10549\n"]],
["White Plains-The Westchester","https://www.tesla.com/findus/location/store/westchester",
["125 Westchester Avenue\n","Suite #1400\n","White Plains, NY 10601\n"]]],

"North Carolina":[["Charlotte-Matthews","https://www.tesla.com/findus/location/store/charlottematthews",
["9140 East Independence Blvd\n","Matthews, NC 28105\n"]],
["Raleigh - Glenwood Avenue","https://www.tesla.com/findus/location/store/raleighglenwoodave",
["7101 Glenwood Avenue\n","Raleigh, NC 27612\n"]]],

"Ohio":[["Cincinnati","https://www.tesla.com/findus/location/store/cincinnati",
["9111 Blue Ash Road\n","Cincinnati, OH 45242\n"]],
["Cleveland-Lyndhurst","https://www.tesla.com/findus/location/store/lyndhurst",
["5180 Mayfield Road\n","Lyndhurst, OH 44124\n"]],
["Columbus","https://www.tesla.com/findus/location/store/columbuseastonloop",
["4099 Easton Loop West\n","Columbus, OH 43219-6087\n"]]],

"Oklahoma":[["Tulsa-6010 S 129th E Ave","https://www.tesla.com/findus/location/store/tulsa6010",
["6010 S 129th E Ave\n","Tulsa, OK 74134\n"]]],

"Oregon":[["Portland-S Macadam Avenue","https://www.tesla.com/findus/location/store/portlandmacadamavenue",
["4330 S Macadam Ave\n","Portland, OR 97239\n"]],
["Portland-Washington Square","https://www.tesla.com/findus/location/store/washingtonsquare",
["9321 SW Washington Square Road Space #T05\n","Portland, OR 97223\n"]]],

"Pennsylvania":[["Devon","https://www.tesla.com/findus/location/store/devon",
["470 W Lancaster Ave\n","Devon, PA 19333\n"]],
["King of Prussia-King of Prussia Mall","https://www.tesla.com/findus/location/store/kingofprussia",
["160 N Gulph Road\n","King of Prussia, PA 19406\n"]],
["Pittsburgh-Wexford","https://www.tesla.com/findus/location/store/pittsburghwexford",
["14010 Perry Highway\n","Wexford, PA 15090\n"]],
["Ross Park Mall","https://www.tesla.com/findus/location/store/rosspark",
["1000 Ross Park Mall Dr Space C02D\n","Pittsburgh, PA 15237\n"]]],

"Rhode Island":[["Warwick","https://www.tesla.com/findus/location/store/warwick",
["399 Bald Hill Road\n","Warwick, RI 02886-1634\n"]]],

"Tennessee":[["Nashville-Brentwood","https://www.tesla.com/findus/location/store/brentwood",
["1641 Westgate Circle\n","Nashville, TN 37027\n"]]],

"Texas":[["Austin-Pond Springs","https://www.tesla.com/findus/location/store/austinpondsprings",
["12845 Research Boulevard\n","Austin, TX 78759\n"]],
["Austin-The Domain","https://www.tesla.com/findus/location/store/thedomain",
["11600 Century Oaks Terrace\n","Austin, TX 78758\n"]],
["Corpus Christi-South Padre Island Drive","https://www.tesla.com/findus/location/store/corpuschristi",
["3605 S Padre Island Dr\n","Corpus Christi, TX 78415\n"]],
["Dallas-Cedar Springs Road","https://www.tesla.com/findus/location/store/cedarspringsroad",
["6500 Cedar Springs Road Suite 100\n","Dallas, TX 75235\n"]],
["Dallas-Northpark Center","https://www.tesla.com/findus/location/store/northparkcenter",
["8687 North Central Expwy Suite #1027\n","Dallas, TX 75225\n"]],
["Fort Worth-Shops at Clearfork","https://www.tesla.com/findus/location/store/fortworth",
["5154 Monahans Avenue\n","Fort Worth, TX 76109\n"]],
["Fort Worth-University Drive","https://www.tesla.com/findus/location/store/fortworthuniversityave",
["275 University Drive\n","Fort Worth, TX 76107\n"]],
["Houston-Houston Galleria","https://www.tesla.com/findus/location/store/houstongalleria",
["5135 West Alabama Street Suite 5270\n","Houston, TX 77056\n"]],
["Houston-North","https://www.tesla.com/findus/location/store/northhouston",
["14820 North Fwy\n","Houston, TX 77090\n"]],
["Market Street-The Woodlands","https://www.tesla.com/findus/location/store/marketstreetthewoodlands",
["9595 Six Pines Drive\n","The Woodlands, TX 77380\n"]],
["Plano-5800 Democracy Drive","https://www.tesla.com/findus/location/store/planodemocracydr",
["5800 Democracy Drive\n","Plano, TX 75024\n"]],
["Plano-Legacy West","https://www.tesla.com/findus/location/store/planotexas",
["7500 Windrose Avenue Space B185\n","Plano, TX 75024\n"]],
["San Antonio-Dominion","https://www.tesla.com/findus/location/store/sanantoniodominion",
["23011 IH-10 West\n","San Antonio, TX 78257\n"]],
["Southlake-Southlake Town Center","https://www.tesla.com/findus/location/store/southlaketowncenter",
["257 Grand Avenue\n","Southlake, TX 76092\n"]],
["Tyler-South Southwest Loop","https://www.tesla.com/findus/location/store/tylersouthservice",
["3408 S SW Loop 323\n","Tyler, TX 75701\n"]]],

"Utah":[["Salt Lake City-S. State Street","https://www.tesla.com/findus/location/store/saltlakecitysstatestreet",
["2312 South State Street\n","South Salt Lake City, UT 84115\n"]]],

"Virginia":[["McLean-Tysons Corner","https://www.tesla.com/findus/location/store/tysonscorner",
["1961 Chain Bridge Rd\n","McLean, VA 22102\n"]],
["Richmond-Glen Allen","https://www.tesla.com/findus/location/store/richmondglenallen",
["9850 W. Broad Street\n","Glen Allen, VA 23060\n"]],
["Tysons Corner-Tyco Road","https://www.tesla.com/findus/location/store/tysonscornertycoroad",
["8500 Tyco Road\n","Vienna, VA 22182\n"]]],

"Washington":[["Bellevue-20th Street","https://www.tesla.com/findus/location/store/bellevue20street",
["14408 NE 20th Street\n","Bellevue, WA 98007\n"]],
["Bellevue-Bellevue Square","https://www.tesla.com/findus/location/store/bellevuesquare",
["223 Bellevue Square Space 104\n","Bellevue, WA 98004\n"]],
["Seattle-Lynnwood","https://www.tesla.com/findus/location/store/seattlelynnwood",
["17731 Highway 99\n","Lynnwood, WA 98037\n"]],
["Seattle-Renton","https://www.tesla.com/findus/location/store/seattlerenton",
["700 S Grady Way\n","Renton, WA 98057-3238\n"]],
["Seattle-Westlake","https://www.tesla.com/findus/location/store/seattlewestlake",
["435 Westlake Avenue N\n","Seattle, WA 98109\n"]],
["University Village","https://www.tesla.com/findus/location/store/universityvillage",
["2627 NE 46th Street\n","Seattle, WA 98105\n"]]],

"Wisconsin":[["Milwaukee","https://www.tesla.com/findus/location/store/milwaukee",
["12011 W Silver Spring Dr\n","Milwaukee, WI 53225-2913\n"]]
}]