INSERT INTO state_data (
vehicle_name,
trim_data,
manufactured_year,
purchase_price,
zero_sixty_mph_in_seconds,
top_speed_mph,
range_in_miles,
interior_options,
seating,
misc_options, 
wheel_options
)
VALUES (
'Model 3',
'Standard Range Plus',
2021,
37990,
5.3,
140,
263,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]',
'[{name:"Five Seat Interior", purchase_price: "included"},{name:"Six Seat Interior", purchase_price: 6500},{name:"Seven Seat Interior", purchase_price: 3500}]'
null,
'[{name:"18 inch Aero Wheels", purchase_price: "included"},{name:"19 inch Sport Wheels", purchase_price: "1500"}]'
),
(
'Model 3',
'Off Menu',
2020,
35000,
5.3,
140,
220,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
null,
null,
'[{name:"18 inch Aero Wheels", purchase_price: "included"},{name:"19 inch Sport Wheels", purchase_price: "1500"}]'
),
(
'Model 3',
'Long Range',
2021,
46990,
4.2,
145,
353,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
null,
null,
'[{name:"18 inch Aero Wheels", purchase_price: "included"},{name:"19 inch Sport Wheels", purchase_price: "1500"}]'
),
(
'Model 3',
'Performance',
2021,
54990,
3.1,
162,
315,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
null,
null,
'[{name:"20 inch Überturbine Wheels", purchase_price:"included"}]'
),
(
'Model S',
'Long Range',
2021,
69420,
3.7,
155,
402,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
null,
null,
'[{name:"19 inch Tempest Wheels", purchase_price:"included"}, {name:"21 inch Sonic Carbon Twin Turbine Wheels", purchase_price:"4500"}]'
),
(
'Model S',
'Performance',
2021,
91990,
2.3,
163,
387,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
null,
null,
'[{name:"19 inch Tempest Wheels", purchase_price:"included"}, {name:"21 inch Sonic Carbon Twin Turbine Wheels", purchase_price:"4500"}]'
),
(
'Model X',
'Long Range',
2021,
4.4,
155,
371,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500},{name:"Cream", purchase_price: 1500}]', 
'[{name:"Five Seat Interior", purchase_price: "included"},{name:"Six Seat Interior", purchase_price: 6500},{name:"Seven Seat Interior", purchase_price: 3500}]',
null,
'[{name:"20 inch Silver Wheels", purchase_price:"included"}, {name:"22 inch Onyx Black Wheels", purchase_price:"5500"}]'
),
(
'Model X',
'Performance',
2021,
2.6,
163,
300,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500},{name:"Cream", purchase_price: 1500}]', 
'[{name:"Five Seat Interior", purchase_price: "included"},{name:"Six Seat Interior", purchase_price: 6500},{name:"Seven Seat Interior", purchase_price: 3500}]',
null,
'[{name:"20 inch Silver Wheels", purchase_price:"included"}, {name:"22 inch Onyx Black Wheels", purchase_price:"5500"}]'
),
(
'Model Y',
'Long Range',
2021,
4.8,
135,
326,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
'[{name:"Five Seat Interior", purchase_price: "included"}]',
'[{name:"Tow Hitch", purchase_price: "1000", description: "High strength, Class II steel tow bar. Capable of towing up to 3,500 lbs"}]',
'[{name:"21 inch Überturbine Wheels", purchase_price:"included"}]'
),
(
'Model Y',
'Performance',
2021,
3.5,
155,
303,
'[{name:"All black", purchase_price: "included"},{name:"Black and White", purchase_price: 1500}]', 
'[{name:"Five Seat Interior", purchase_price: "included"}]',
'[{name:"Tow Hitch", purchase_price: "1000", description: "High strength, Class II steel tow bar. Capable of towing up to 3,500 lbs"}]',
'[{name:"21 inch Überturbine Wheels", purchase_price:"included"}]'
)
