export const GET_ALL_VEHICLES = "GET_ALL_VEHICLES";
export const GET_ALL_VEHICLES_ERROR = "GET_ALL_VEHICLES_ERROR";
export const GET_ALL_ZIPCODE_DATA = "GET_ALL_ZIPCODE_DATA";
export const GET_ALL_ZIPCODE_DATA_ERROR = "GET_ALL_ZIPCODE_DATA_ERROR";
export const GET_ALL_US_STATES_DATA = "GET_ALL_US_STATES_DATA";
export const GET_ALL_US_STATES_DATA_ERROR = "GET_ALL_US_STATES_DATA_ERROR";
